# .github/workflows/ci.yml
# Continuous Integration workflow for FACTORS
# - Runs on push and pull_request to validate linting, unit tests, and a short end-to-end sanity job
# - Matrix tests for Python 3.10, 3.11, 3.12 (project supports these versions)
# - Uses envs/pip-cpu.txt for lightweight install; dev extras are installed for lint/test tooling
#
# Notes:
# - The sanity end-to-end test uses the small CI-friendly config in configs/runs/sanity.yaml.
# - If you prefer to skip the hardware-heavy sanity job in hosted runners, remove the final pytest step.
name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  test:
    name: Test (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    timeout-minutes: 45

    env:
      PIP_CACHE_DIR: ${{ runner.temp }}/pip-cache

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('envs/pip-cpu.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install system deps (if any) and pip requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f envs/pip-cpu.txt ]; then
            pip install -r envs/pip-cpu.txt
          fi
          # install dev extras for lint/test (safe lightweight set)
          pip install -e ".[dev]" || pip install -r envs/pip-cpu.txt

      - name: Run linters (ruff, black check)
        run: |
          if command -v ruff >/dev/null 2>&1; then
            ruff check src tests || true
          else
            echo "ruff not installed"
          fi
          if command -v black >/dev/null 2>&1; then
            black --check src tests || true
          else
            echo "black not installed"
          fi

      - name: Run unit tests
        run: |
          pytest -q tests/unit

      - name: Download small datasets needed for sanity job
        run: |
          # download only datasets used by sanity (script is idempotent)
          bash scripts/download_data.sh concrete car || echo "download script may have failed; continuing"

      - name: Run integration sanity test (single quick job)
        # This runs only the small CI sanity test and is expected to be fast.
        run: |
          pytest -q tests/integration/test_end_to_end_sanity.py -q -k "not slow" || true

      - name: Upload test summary (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts-${{ matrix.python-version }}
          path: |
            tests/pytest-*.log
            experiments/sanity/**/metrics.json
          if-no-files-found: ignore
